### ISSUE TITLE
Bunker cards

### ISSUE THREAD

**Issue by bundasht** [VladStatsenko/BunkerGame#1]
Привет Влад. 
Я делаю бота в дискорде для игры Бункер и хотел спросить могу ли я использовать карты игроков с твоего репо и откуда ты их взял(надо еще карты бункера). 
Можешь отписать тут или написать как с тобой связаться. 

Спасибо большое.

**Comment by VladStatsenko** [comment]
Напиши в телеграм @vstatsenko

**Comment by bundasht** [comment]
resolved
